package org.GameLogic.Communication;

import java.util.List;

import org.GameLogic.DataStructures.Player;

import de.upb.swtpra1819interface.models.Tile;

/**
 * This interface does structure the responses that are generated by
 * asynchronous events in the <i>GameHandler</i>
 */
public interface CommunicationHandlerCallback {

	/**
	 * Callback for kicking a player
	 * 
	 * @param player Player object
	 */
	public void callbackPlayerKicked(Player player);

	/**
	 * Callback for cycling to next player
	 * 
	 * @param player Player object
	 */
	public void callbackNextPlayer(Player player);

	/**
	 * Callback for playing tiles
	 * 
	 * @param player       Player object
	 * @param newHandTiles Tiles a player played
	 */
	public void callbackPlayerTiles(Player player, List<Tile> newHandTiles);

	/**
	 * Callback for game finish
	 */

	public void callbackGameFinish(boolean rightfullyFinished);
}
